# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/StathisKratimenos/Colab/blob/main/Welcome_to_Colab.ipynb
"""

import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

#1. Δομή του πίνακα
df.head()  # Δείχνει τις πρώτες 5 γραμμές

df.info()          # Πληροφορίες στηλών, τύποι δεδομένων
df.describe()      # Στατιστικά για αριθμητικά πεδία

df.isnull().sum() #2. Έλεγχος για ελλιπή δεδομένα

#3. Επιλογή συγκεκριμένων στηλών
df[['Name', 'Sex', 'Survived']].head()

#4. Φιλτράρισμα: Ποιοι άντρες δεν επιβίωσαν;
df[(df['Sex'] == 'male') & (df['Survived'] == 0)]

#5. Ομαδοποίηση: Ποσοστά επιβίωσης ανά φύλο
df.groupby('Sex')['Survived'].mean()

#Ποια ηλικιακή ομάδα (0–18, 19–50, 51+) είχε τα μεγαλύτερα ποσοστά επιβίωσης;
bins = [0, 18, 50, 100]
labels = ['Παιδια-Εφηβοι', 'Ενηλικες', 'Ηλικιωμενοι']

df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)

df[['Age', "AgeGroup"]].head(5)

df.groupby('AgeGroup')['Survived'].mean()

df.groupby('Pclass')['Survived'].mean()

import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(x='Pclass', y='Survived', data=df)
plt.title('Ποσοστά Επιβίωσης ανά Κατηγορία Εισιτηρίου')
plt.show()

